{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  namespace: {{ $.Values.global.namespace }}
data:
  SPRING_PROFILES_ACTIVE: "prod"
{{- end }}
