{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{- range $name, $svc := .Values.services }}
          - path: {{ $svc.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: 80
        {{- end }}
{{- end }}
