{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secrets
  namespace: {{ $.Values.global.namespace }}
type: Opaque
stringData:
  DB_USER: "REPLACE_ME"
  DB_PASSWORD: "REPLACE_ME"
{{- end }}
