{{- if .Values.serviceAccount.create }}
{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  annotations:
    {{- toYaml $.Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
