apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service-monitor
  namespace: microservices
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: product-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
