apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  namespace: microservices
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/product-service-irsa-role
