apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: microservices
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "userdb.microservices.svc.cluster.local"
  DB_PORT: "5432"
